#!/usr/bin/env fish

argparse -n 'install.fish' -X 0 \
    'h/help' \
    'noconfirm' \
    'aur-helper=!contains -- "$_flag_value" yay paru' \
    -- $argv
or exit

# Print help
if set -q _flag_h
    echo 'usage: ./install.fish [-h] [--noconfirm] [--aur-helper=yay|paru]'
    echo
    echo 'Installs the my-caelestia dots + every app the user always wants:'
    echo '  spotify (+spicetify), discord (+OpenAsar+Equicord), visual-studio-code-bin,'
    echo '  obsidian, cursor-bin.'
    echo
    echo 'options:'
    echo '  -h, --help                  show this help message and exit'
    echo '  --noconfirm                 do not confirm package installation'
    echo '  --aur-helper=[yay|paru]     the AUR helper to use (default: paru)'

    exit
end


# Helper funcs
function _out -a colour text
    set_color $colour
    # Pass arguments other than text to echo
    echo $argv[3..] -- ":: $text"
    set_color normal
end

function log -a text
    _out cyan $text $argv[2..]
end

function input -a text
    _out blue $text $argv[2..]
end

function sh-read
    sh -c 'read a && echo -n "$a"' || exit 1
end

function confirm-overwrite -a path
    if test -e $path -o -L $path
        # No prompt if noconfirm
        if set -q noconfirm
            input "$path already exists. Overwrite? [Y/n]"
            log 'Removing...'
            rm -rf $path
        else
            # Prompt user
            input "$path already exists. Overwrite? [Y/n] " -n
            set -l confirm (sh-read)

            if test "$confirm" = 'n' -o "$confirm" = 'N'
                log 'Skipping...'
                return 1
            else
                log 'Removing...'
                rm -rf $path
            end
        end
    end

    return 0
end


# Variables
set -q _flag_noconfirm && set noconfirm '--noconfirm'
set -q _flag_aur_helper && set -l aur_helper $_flag_aur_helper || set -l aur_helper paru
set -q XDG_CONFIG_HOME && set -l config $XDG_CONFIG_HOME || set -l config $HOME/.config
set -q XDG_STATE_HOME && set -l state $XDG_STATE_HOME || set -l state $HOME/.local/state
set -l install_dir (path dirname (path resolve (status filename)))

# Startup prompt
set_color magenta
echo '╭─────────────────────────────────────────────────╮'
echo '│      ______           __          __  _         │'
echo '│     / ____/___ ____  / /__  _____/ /_(_)___ _   │'
echo '│    / /   / __ `/ _ \/ / _ \/ ___/ __/ / __ `/   │'
echo '│   / /___/ /_/ /  __/ /  __(__  ) /_/ / /_/ /    │'
echo '│   \____/\__,_/\___/_/\___/____/\__/_/\__,_/     │'
echo '│                                                 │'
echo '╰─────────────────────────────────────────────────╯'
set_color normal
log 'Welcome to the Caelestia dotfiles installer!'
log 'Before continuing, please ensure you have made a backup of your config directory.'

# Prompt for backup
if ! set -q _flag_noconfirm
    log '[1] Two steps ahead of you!  [2] Make one for me please!'
    input '=> ' -n
    set -l choice (sh-read)

    if contains -- "$choice" 1 2
        if test $choice = 2
            log "Backing up $config..."

            if test -e $config.bak -o -L $config.bak
                input 'Backup already exists. Overwrite? [Y/n] ' -n
                set -l overwrite (sh-read)

                if test "$overwrite" = 'n' -o "$overwrite" = 'N'
                    log 'Skipping...'
                else
                    rm -rf $config.bak
                    cp -r $config $config.bak
                end
            else
                cp -r $config $config.bak
            end
        end
    else
        log 'No choice selected. Exiting...'
        exit 1
    end
end


# Install AUR helper if not already installed
if ! pacman -Q $aur_helper &> /dev/null
    log "$aur_helper not installed. Installing..."

    # Install
    sudo pacman -S --needed git base-devel $noconfirm
    cd /tmp
    git clone https://aur.archlinux.org/$aur_helper.git
    cd $aur_helper
    makepkg -si
    cd ..
    rm -rf $aur_helper

    # Setup
    if test $aur_helper = yay
        $aur_helper -Y --gendb
        $aur_helper -Y --devel --save
    else
        $aur_helper --gendb
    end
end

# Cd into dir
cd $install_dir || exit 1

# Install metapackage for deps
log 'Installing metapackage...'

if test $aur_helper = yay
    $aur_helper -Bi . $noconfirm
else
    $aur_helper -Ui $noconfirm
end
fish -c 'rm -f caelestia-meta-*.pkg.tar.zst' 2> /dev/null

# Install hypr* configs
if confirm-overwrite $config/hypr
    log 'Installing hypr* configs...'
    ln -s (realpath hypr) $config/hypr
    chmod u+x $config/hypr/scripts/volstep.fish
    hyprctl reload
end

# Install caelestia user-config files (shell.json + hypr-user.lua).
# These live INSIDE this repo (under ./caelestia) so they're version-controlled
# with the rest of the dots. They're symlinked file-by-file into ~/.config/caelestia
# because that directory also holds Hyprland-autogenerated state (monitors/).
log 'Installing caelestia user configs...'
mkdir -p $config/caelestia
for f in shell.json hypr-user.lua
    if confirm-overwrite $config/caelestia/$f
        ln -s (realpath caelestia/$f) $config/caelestia/$f
    end
end

# Starship
if confirm-overwrite $config/starship.toml
    log 'Installing starship config...'
    ln -s (realpath starship.toml) $config/starship.toml
end

# Foot
if confirm-overwrite $config/foot
    log 'Installing foot config...'
    ln -s (realpath foot) $config/foot
end

# Fish
if confirm-overwrite $config/fish
    log 'Installing fish config...'
    ln -s (realpath fish) $config/fish
end

# Fastfetch
if confirm-overwrite $config/fastfetch
    log 'Installing fastfetch config...'
    ln -s (realpath fastfetch) $config/fastfetch
end

# Uwsm
if confirm-overwrite $config/uwsm
    log 'Installing uwsm config...'
    ln -s (realpath uwsm) $config/uwsm
end

# Btop
if confirm-overwrite $config/btop
    log 'Installing btop config...'
    ln -s (realpath btop) $config/btop
end

# Spotify (+ Spicetify with caelestia theme)
log 'Installing spotify (spicetify)...'

set -l has_spicetify (pacman -Q spicetify-cli 2> /dev/null)
$aur_helper -S --needed spotify spicetify-cli spicetify-marketplace-bin $noconfirm

# Set permissions and init if new install
if test -z "$has_spicetify"
    sudo chmod a+wr /opt/spotify
    sudo chmod a+wr /opt/spotify/Apps -R
    spicetify backup apply
end

# Install configs
if confirm-overwrite $config/spicetify
    log 'Installing spicetify config...'
    ln -s (realpath spicetify) $config/spicetify

    # Set spicetify configs
    spicetify config current_theme caelestia color_scheme caelestia custom_apps marketplace 2> /dev/null
    spicetify apply
end

# Visual Studio Code (proprietary build) + caelestia-vscode-integration extension
log 'Installing visual-studio-code-bin...'
$aur_helper -S --needed visual-studio-code-bin $noconfirm

set -l vscode_folder $config/Code/User
if confirm-overwrite $vscode_folder/settings.json && confirm-overwrite $vscode_folder/keybindings.json && confirm-overwrite $config/code-flags.conf
    log 'Installing vscode config...'
    mkdir -p $vscode_folder
    ln -s (realpath vscode/settings.json) $vscode_folder/settings.json
    ln -s (realpath vscode/keybindings.json) $vscode_folder/keybindings.json
    ln -s (realpath vscode/flags.conf) $config/code-flags.conf

    # Install caelestia integration extension
    code --install-extension vscode/caelestia-vscode-integration/caelestia-vscode-integration-*.vsix
end

# Discord (OpenAsar + Equicord)
log 'Installing discord...'
$aur_helper -S --needed discord equicord-installer-bin $noconfirm
sudo Equilotl -install -location /opt/discord
sudo Equilotl -install-openasar -location /opt/discord
$aur_helper -Rns equicord-installer-bin $noconfirm

# Obsidian (official extra repo, not AUR)
log 'Installing obsidian...'
sudo pacman -S --needed obsidian $noconfirm

# Cursor (AUR)
log 'Installing cursor-bin...'
$aur_helper -S --needed cursor-bin $noconfirm

# Generate scheme stuff if needed
if ! test -f $state/caelestia/scheme.json
    caelestia scheme set -n shadotheme
    sleep .5
    hyprctl reload
end

# Start the shell
caelestia shell -d > /dev/null

log 'Done!'
